Graduation_Work_With_Django/Graduation_Work_With_Django/urls.py
from django.contrib import admin
from django.urls import path, include

handler403 = 'RRIT.views.handler403'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('RRIT.urls')),
    path('Incidents/', include('Incidents.urls')),
    path('users/', include('users.urls', namespace="users")),
    path('Subdivisions/', include('Subdivisions.urls')),
   # path("__debug__/", include("debug_toolbar.urls")),
]

Graduation_Work_With_Django/RRIT/urls.py
from django.urls import path

from users.views import login_user
from .views import *

urlpatterns = [
    path('', index, name='home'),
]

Graduation_Work_With_Django/users/urls.py
from django.urls import path

from .views import *

app_name = "users"

urlpatterns = [
    path('login/', login_user, name='login'),  # http://127.0.0.1:8000/Incidents/id/
    path('logout/', logout_user, name='logout'),  # http://127.0.0.1:8000/Incidents/id/
    path('', users_all, name='Users_all'),  # http://127.0.0.1:8000/Incidents - Users из мейн файла urls

    path('Position/', users_positions, name='users_positions'),  # http://127.0.0.1:8000/Incidents - Users из мейн файла urls
    path('Position/?', users_positions_search, name='Positions_search'),
    path('Position/<int:PositionID>/', users_positions_id, name='Positions_id'),
    path('Position/add/', users_positions_add, name='Positions_add'),
    path('Position/<int:PositionID>/change/', users_positions_change, name='Positions_change'),
    path('Position/<int:PositionID>/delete/', users_positions_delete, name='Positions_delete'),

    path('<int:UsersID>/', user_id, name='User_ID'),  # http://127.0.0.1:8000/Incidents/id/
    path('<int:UsersID>/delete/', user_delete, name='user_delete'),  # http://127.0.0.1:8000/Incidents/id/
    path('?', users_search, name='Users_search'),
]

Graduation_Work_With_Django/RRIT/models.py
from django.db import models

# Create your models here.

Graduation_Work_With_Django/RRIT/views.py
from django.contrib.auth.decorators import user_passes_test, login_required
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.shortcuts import render, redirect
from Graduation_Work_With_Django import settings
from django.apps import apps

all_models = []
def permission_edit_required(perm, login_url=None, raise_exception=True):
    def check_perms(user):
        if isinstance(perm, str):
            perms = (perm, )
        else:
            perms = perm
        if user.has_perms(perms):
            return True
        if raise_exception and user.pk:
            raise PermissionDenied
        return False
    return user_passes_test(check_perms, login_url=login_url)
def get_sidebar(request):

    list1 = apps.get_models()
    app_models = []
    array_of_permissions_help = []   #есть список моделей
    array_of_permissions=[]
    for model1 in list1:
        if model1._meta.app_label == 'Incidents' or model1._meta.app_label == 'users' or model1._meta.app_label == 'Subdivisions':
            for key in model1._meta.permissions:
                array_of_permissions_help.append(model1._meta.app_label + '.' + key[0])
            for help in array_of_permissions_help:
                if help in request.user.get_group_permissions() and help not in array_of_permissions:
                    array_of_permissions.append(help)
    array_of_permissions_help = []
    array_of_event = {'add', 'change', 'delete', 'id', 'all', 'map'}
    for model1 in list1:
        if model1._meta.app_label == 'Incidents' or model1._meta.app_label == 'users' or model1._meta.app_label == 'Subdivisions':
            help_array = []
            for model in list1:
                if model._meta.app_label == model1._meta.app_label:
                    if model._meta.object_name not in help_array:
                        if model._meta.app_label == 'Incidents' and model._meta.object_name == 'Incidents':
                            add_url = ''
                            change_url = ''
                            delete_url = ''
                            url_view = ''
                            id = ''
                            map=''
                            view_model = ''
                            if request.user.has_perm('Incidents.Incidents.incidents_add'):
                                add_url = '/' + model._meta.app_label + '/add/'
                            if request.user.has_perm('Incidents.Incidents.incidents_change'):
                                change_url = '/' + model._meta.app_label + '/change/'
                            if request.user.has_perm('Incidents.Incidents.incidents_delete'):
                                delete_url = 'delete/'
                            if request.user.has_perm('Incidents.Incidents.incidents_id'):
                                id='id/'
                            if request.user.has_perm('Incidents.Incidents.incidents_map'):
                                map='map/'
                            if request.user.has_perm('Incidents.Incidents.incidents_all'):
                                url_view = '/' + model._meta.app_label + '/'
                            if add_url=='' and change_url == '' and url_view == '':
                                view_model = ''
                            else:
                                view_model = '1'
                            if view_model != '':
                                help_array.append({
                                    'name': model._meta.verbose_name_plural,
                                    'app_label': model._meta.object_name,
                                    'url_view': url_view,
                                    'add_url': add_url,
                                    'change_url': change_url,
                                    'delete_url':delete_url,
                                    'id': id,
                                    'map': map,
                                    'view_model':view_model
                                }
                            )
                        if model._meta.app_label == 'Incidents' and model._meta.object_name == 'Specifications':

                            add_url = ''
                            change_url = ''
                            delete_url = ''
                            url_view = ''
                            id = ''
                            map=''
                            view_model = ''
                            if request.user.has_perm('Specifications.Incidents.incidents_add'):
                                add_url = '/' + model._meta.app_label + '/' + model._meta.object_name[:-1] + '/' + 'add/'
                            if request.user.has_perm('Specifications.Incidents.incidents_change'):
                                change_url = '/' + model._meta.app_label + '/' + model._meta.object_name[
                                                                                  :-1] + '/' + 'change/'
                            if request.user.has_perm('Specifications.Incidents.incidents_delete'):
                                delete_url = 'delete/'
                            if request.user.has_perm('Specifications.Incidents.incidents_id'):
                                id='id/'
                            if request.user.has_perm('Specifications.Incidents.incidents_map'):
                                map='map/'
                            if request.user.has_perm('Specifications.Incidents.incidents_all'):
                                url_view = '/' + model._meta.app_label + '/' + model._meta.object_name[:-1] + '/'
                            if add_url == '' and change_url == '' and url_view == '':
                                view_model = ''
                            else:
                                view_model = '1'
                            if view_model != '':
                                help_array.append({
                                'name': model._meta.verbose_name_plural,
                                'app_label': model._meta.object_name,
                                'url_view': url_view,
                                'add_url': add_url,
                                'change_url': change_url,
                                'delete_url': delete_url,
                                'id': id,
                                'map': map,
                                'view_model': view_model
                            }
                            )
                        if model._meta.app_label == 'Incidents' and model._meta.object_name == 'Status':
                            add_url = ''
                            change_url = ''
                            delete_url = ''
                            url_view = ''
                            id = ''
                            map = ''
                            view_model = ''
                            if request.user.has_perm('Status.Incidents.incidents_add'):
                                add_url = '/' + model._meta.app_label + '/' + model._meta.object_name + '/' + 'add/'
                            if request.user.has_perm('Status.Incidents.incidents_change'):
                                change_url = '/' + model._meta.app_label + '/' + model._meta.object_name + '/' + 'change/'
                            if request.user.has_perm('Status.Incidents.incidents_delete'):
                                delete_url = 'delete/'
                            if request.user.has_perm('Status.Incidents.incidents_id'):
                                id = 'id/'
                            if request.user.has_perm('Status.Incidents.incidents_map'):
                                map = 'map/'
                            if request.user.has_perm('Status.Incidents.incidents_all'):
                                url_view = '/' + model._meta.app_label + '/' + model._meta.object_name + '/'

                            if add_url == '' and change_url == '' and url_view == '':
                                view_model = ''
                            else:
                                view_model = '1'
                            if view_model != '':
                                help_array.append({
                                    'name': model._meta.verbose_name_plural,
                                    'app_label': model._meta.object_name,
                                    'url_view': url_view,
                                    'add_url': add_url,
                                    'change_url': change_url,
                                'delete_url': delete_url,
                                'id': id,
                                'map': map,
                                'view_model':view_model
                                })


                        if model._meta.app_label == 'users' and model._meta.object_name == 'User':
                            add_url = ''
                            change_url = ''
                            delete_url = ''
                            url_view = ''
                            id = ''
                            map = ''
                            view_model = ''
                            if request.user.has_perm('users.users.user_delete'):
                                delete_url = 'delete/'
                            if request.user.has_perm('users.users.user_id'):
                                id = 'id/'
                            if request.user.has_perm('users.users.user_all'):
                                url_view = '/' + model._meta.app_label + '/'
                            if add_url == '' and change_url == '' and url_view == '':
                                view_model = ''
                            else:
                                view_model = '1'
                            if view_model != '':
                                help_array.append({

Graduation_Work_With_Django/RRIT/templates/RRIT/index.html
{% load i18n static %}
<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:" ru-ru" }}" dir="{{ LANGUAGE_BIDI|yesno:'rtl,ltr,auto' }}">
<head>
    <title></title>
    <link rel="stylesheet" href="{% block stylesheet %}{% static 'admin/css/base.css' %}{% endblock %}">

    {% block dark-mode-vars %}
    <link rel="stylesheet" href="{% static 'admin/css/dark_mode.css' %}">
    <script src="{% static 'admin/js/theme.js' %}" defer></script>
    {% endblock %}
    <link rel="stylesheet" href="{% static 'admin/css/nav_sidebar.css' %}">
    <script src="{% static 'admin/js/nav_sidebar.js' %}" defer></script>
    <script src="{% static "bootstrap/js/bootstrap.bundle.min.js" %}"></script>

    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.css" %} " />
    {% block extrastyle %}{% endblock %}
    {% if LANGUAGE_BIDI %}
    <link rel="stylesheet" href="{% block stylesheet_rtl %}{% static 'admin/css/rtl.css' %}{% endblock %}">
    {% endif %}
    {% block extrahead %}


    <link rel="stylesheet" href="{% static 'admin/css/dashboard.css' %}">
    {% endblock %}
    {% block responsive %}
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" href="{% static 'admin/css/responsive.css' %}">
    {% if LANGUAGE_BIDI %}
    <link rel="stylesheet" href="{% static 'admin/css/responsive_rtl.css' %}">
    {% endif %}

    {% endblock %}
    {% block blockbots %}
    <meta name="robots" content="NONE,NOARCHIVE">
    {% endblock %}
</head>
<body class="{% block bodyclass %} dashboard {% endblock %}" data-admin-utc-offset="{% now " Z" %}">


<!-- Container -->
<div id="container">
    <!-- Header -->
    {% block header %}
    <div id="header">
        <div id="branding">
            {% block branding %}
            <img src="{% static '/images/logo.png' %}" width="100px" height="50px" alt="RZD">
            <h1 id="site-name" style="margin: 5px"><a href="{% url 'home' %}">Отслеживание происшествий ОАО "РЖД"</a>
            </h1>
            {% endblock %}
        </div>
        {% block usertools %}
        <div id="user-tools">

            {% block welcome-msg %}
            Добро пожаловать,
            <strong>{{user.surname}} {{user.name}}</strong>.
            {% endblock %}
            {% block userlinks %}

            {% if user.is_active and user.is_staff %}
            {% url 'django-admindocs-docroot' as docsroot %}
            {% if docsroot %}
            <a href="{{ docsroot }}">{% translate 'Documentation' %}</a> /
            {% endif %}
            {% endif %}
            {% if user.has_usable_password %}
            <a href="{% url 'admin:password_change' %}">{% translate 'Change password' %}</a> /
            {% endif %}
            <a href="{% url "users:logout"%}">{% translate 'Log out' %}</a>
            {% include "admin/color_theme_toggle.html" %}
            {% endblock %}
        </div>
        {% endblock %}
        {% block nav-global %}{% endblock %}
    </div>
    {% endblock %}
    <!-- END Header -->


    {% block nav-breadcrumbs %}

    {% endblock %}

    <div class="main" id="main">
        {% block nav-sidebar %}

        {% endblock %}
        <div id="content-start" class="content" tabindex="-1">
            {% block messages %}
            {% if messages %}
            <ul class="messagelist">{% for message in messages %}
                <li
                        {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message|capfirst }}
                </li>
                {% endfor %}
            </ul>
            {% endif %}
            {% endblock messages %}
            <!-- Content -->
            <div id="content" class="{% block coltype %}colM{% endblock %}">
                {% block pretitle %}{% endblock %}

                {% block content %}
                <div id="content-main">

                    {% block object-tools %}

                    {% for app in app_models %}
                    <div class="app-{{ app.app_label }} module{% if app.app_url in request.path|urlencode %} current-app{% endif %}">
                        <table>

                            {% for key, value in app.items %}
                            <caption>

                                <a href="#" class="section"
                                   title="{% blocktranslate with name=key %}Models in the {{ key }} application{% endblocktranslate %}">
                                    {% if key == 'users'%}
                                    Пользователи
                                    {% elif key == 'Incidents' %}
                                    Происшествия
                                    {% elif key == 'Subdivisions' %}
                                    Подразделения
                                    {% endif %}
                                </a>
                            </caption>
                            {% for value1 in value %}

                            {% if value1.url_view == '' and value1.add_url == '' %}
                            {% else %}
                            <tr class="model-{{ value1.app_label }}  {% if action_model in value1.app_label %} current-model {% endif %}">
                                <th scope="row">
                                {% if value1.url_view == ''  %}
                                {{ value1.name}}
                                    {% else %}
                                <a href="{{ value1.url_view }}" aria-current="page">{{ value1.name}}</a>
                                  {% endif %}
                                </th>

                                {% if value1.add_url == ''   %}
                                <td><a href="" class="addlink"></a></td>
                                {% else %}
                                <td><a href="{{ value1.add_url }}" class="addlink">{% translate 'Add' %}</a></td>
                                {% endif %}
                            </tr>
                            {% endif %}
                            {% endfor %}


                            {% endfor %}
                        </table>
                    </div>

                    {% endfor %}


                </div>
                {% endblock %}

                {% endblock %}
                {% block sidebar %}
                {% include "RRIT/logs.html" %}
                {% endblock %}
                <br class="clear">
            </div>
            <!-- END Content -->
            {% block footer %}
            <div id="footer"></div>
            {% endblock %}
        </div>
    </div>
</div>
<!-- END Container -->

<!-- SVGs -->
<svg xmlns="http://www.w3.org/2000/svg" class="base-svgs">
    <symbol viewBox="0 0 24 24" width="1rem" height="1rem" id="icon-auto">
        <path d="M0 0h24v24H0z" fill="currentColor"/>
        <path d="M12 22C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10-4.477 10-10 10zm0-2V4a8 8 0 1 0 0 16z"/>
    </symbol>
    <symbol viewBox="0 0 24 24" width="1rem" height="1rem" id="icon-moon">
        <path d="M0 0h24v24H0z" fill="currentColor"/>
        <path d="M10 7a7 7 0 0 0 12 4.9v.1c0 5.523-4.477 10-10 10S2 17.523 2 12 6.477 2 12 2h.1A6.979 6.979 0 0 0 10 7zm-6 5a8 8 0 0 0 15.062 3.762A9 9 0 0 1 8.238 4.938 7.999 7.999 0 0 0 4 12z"/>
    </symbol>
    <symbol viewBox="0 0 24 24" width="1rem" height="1rem" id="icon-sun">
        <path d="M0 0h24v24H0z" fill="currentColor"/>
        <path d="M12 18a6 6 0 1 1 0-12 6 6 0 0 1 0 12zm0-2a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM11 1h2v3h-2V1zm0 19h2v3h-2v-3zM3.515 4.929l1.414-1.414L7.05 5.636 5.636 7.05 3.515 4.93zM16.95 18.364l1.414-1.414 2.121 2.121-1.414 1.414-2.121-2.121zm2.121-14.85l1.414 1.415-2.121 2.121-1.414-1.414 2.121-2.121zM5.636 16.95l1.414 1.414-2.121 2.121-1.414-1.414 2.121-2.121zM23 11v2h-3v-2h3zM4 11v2H1v-2h3z"/>
    </symbol>
</svg>
</body>
</html>

Graduation_Work_With_Django/RRIT/templates/RRIT/logs.html
{% load i18n static %}
{% block sidebar %}

<div id="content-related">
    <div class="module" id="recent-actions-module">
        <h2>{% translate 'Recent actions' %}</h2>
        <h3>{% translate 'My actions' %}</h3>
        {% load log %}
        {% get_admin_log 10 as admin_log for_user user %}
        {% if not admin_log %}
        <p>{% translate 'None available' %}</p>
        {% else %}
        <ul class="actionlist">
            {% for entry in admin_log %}
            <li class="{% if entry.is_addition %}addlink{% endif %}{% if entry.is_change %}changelink{% endif %}{% if entry.is_deletion %}deletelink{% endif %}">
                {% if entry.is_deletion or not entry.get_admin_url %}
                {{ entry.object_repr }}
                {% else %}
                <a href="{{ entry.get_admin_url }}">{{ entry.object_repr }}</a>
                {% endif %}
                <br>
                {% if entry.content_type %}
                <span class="mini quiet">{% filter capfirst %}{{ entry.content_type.name }}{% endfilter %}</span>
                {% else %}
                <span class="mini quiet">{% translate 'Unknown content' %}</span>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</div>


{% endblock %}

Graduation_Work_With_Django/RRIT/templates/RRIT/nav_sidebar.html
{% load i18n %}
<button class="sticky toggle-nav-sidebar" id="toggle-nav-sidebar"
        aria-label="{% translate 'Toggle navigation' %}"></button>
<nav class="sticky" id="nav-sidebar" aria-label="{% translate 'Sidebar' %}">
    <input type="search" id="nav-filter"
           placeholder="{% translate 'Start typing to filter…' %}"
           aria-label="{% translate 'Filter navigation items' %}">

{% for app in app_models %}
                    <div class="app-{{ app.app_label }} module{% if app.app_url in request.path|urlencode %} current-app{% endif %}">
                        <table>

                            {% for key, value in app.items %}
                            <caption>

                                <a href="#" class="section"
                                   title="{% blocktranslate with name=key %}Models in the {{ key }} application{% endblocktranslate %}">
                                    {% if key == 'users'%}
                                    Пользователи
                                    {% elif key == 'Incidents' %}
                                    Происшествия
                                    {% elif key == 'Subdivisions' %}
                                    Подразделения
                                    {% endif %}
                                </a>
                            </caption>
                            {% for value1 in value %}

                            {% if value1.url_view == '' and value1.add_url == '' %}
                            {% else %}
                            <tr class="model-{{ value1.app_label }}  {% if action_model in value1.app_label %} current-model {% endif %}">

                                <th scope="row">
                                {% if value1.url_view == ''  %}
                                {{ value1.name}}
                                    {% else %}
                                <a href="{{ value1.url_view }}" aria-current="page">{{ value1.name}}</a>
                                  {% endif %}
                                </th>

                                {% if value1.add_url == ''   %}
                                <td><a href="" class=""></a></td>
                                {% else %}
                                <td><a href="{{ value1.add_url }}" class="addlink">{% translate 'Add' %}</a></td>
                                {% endif %}
                            </tr>
                            {% endif %}
                            {% endfor %}


                            {% endfor %}
                        </table>
                    </div>

                    {% endfor %}

</nav>

Graduation_Work_With_Django/RRIT/templates/RRIT/navigation.html
{% load i18n static %}
{% block nav-breadcrumbs %}
<nav aria-label="{% translate 'Breadcrumbs' %}">
    {% block breadcrumbs %}
    <div class="breadcrumbs">

        <a href="{% url 'home' %}">{% translate 'Home' %}</a>
        &rsaquo;
        {% if function_name == "views_all" %}
        {{ ru_name_all }}

        {% endif %}

    </div>
    {% endblock %}
</nav>


{% endblock %}

Graduation_Work_With_Django/RRIT/templates/RRIT/view_all.html
{% extends "RRIT/index.html" %}
{% load i18n admin_urls static admin_list %}

{% block extrastyle %}
 {{ block.super }}
  <link rel="stylesheet" href="{% static "admin/css/changelists.css" %}">
    <script src="{% url 'admin:jsi18n' %}"></script>
{% endblock %}

{% block extrahead %}
{{ block.super }}
{% endblock %}

{% block bodyclass %} app-{{ action_model }} model-{{ action_models_s }} change-list{% endblock %}
{% block sidebar %}
{% endblock %}
{% block nav-breadcrumbs %}
{% include "RRIT/navigation.html" %}

{% endblock %}


{% block nav-sidebar %}
{% include "RRIT/nav_sidebar.html" %}
{% endblock %}
{% block content %}
<h1>Выберите {{ru_name_single}} для изменения</h1>
<div id="content-main">
    {% block coltype %}{% endblock %}
    {% block object-tools %}
    <ul class="object-tools">
        <li>
            <a href="add/" class="addlink"> Добавить {{ru_name_single}}

            </a>
        </li>
    </ul>
    {% endblock %}
    <div class="module" id="changelist">
        <div class="changelist-form-container">
            <div id="toolbar">
                <form id="" action="%3F" method="get">
                        <label for="searchbar"><img src="{% static "admin/img/search.svg" %}" alt="Search"></label>
                        <input type="text" size="40" name="search" value="" id="searchbar">
                        <input type="submit" value="{% translate 'Search' %}">
                </form>
            </div>

            <form id="changelist-form" method="post" novalidate=""><input type="hidden" name="csrfmiddlewaretoken"
                                                                          value="I392hWKAYLrydLjSWmAs176fiTun39UOhMgEujVVvIbD1JY7g4aorJklbS6kxn8q">
                <div class="actions">
                    <label>Действие: <select name="action" required="">
                        <option value="" selected="">---------</option>
                        <option value="delete_selected">Удалить выбранные Инциденты</option>
                    </select></label><input type="hidden" name="select_across" value="0" class="select-across">
                    <button type="submit" class="button" title="Выполнить выбранное действие" name="index" value="0">
                        Выполнить
                    </button>
                    <span class="action-counter" data-actions-icnt="1">Выбрано 0 объектов из 1 </span>
                </div>
                {% if array_of_data|length %}
                <div class="results">
                    <table id="result_list">
                        <thead>
                        <tr>
                            <th scope="col" class="action-checkbox-column">
                                <div class="text"><span><input type="checkbox" id="action-toggle"></span></div>
                                <div class="clear"></div>
                            </th>

                            {% for th in array_of_th %}
                            <th scope="col" class="column-__str__">
                                <div class="text"><span>{{ th }}</span></div>
                                <div class="clear"></div>
                            </th>
                            {% endfor %}


                        </tr>
                        </thead>
                        <tbody>
                        {% for data in array_of_data %}
                        <tr>
                            {% for key, value in data.items %}
                                          <td class="action-checkbox"><input type="checkbox" name="_selected_action" value="{{ key }}"
                                                               class="action-select"></td>
                            {% for down_value in value%}
                            {% for key1, value1 in down_value.items %}
                            <th class="field-{{ key1 }}">

                                {% if action_model == 'Specifications'%}
<a href="/{{ start_model }}/{{action_models_s}}/{{ key }}/">
                                {% elif action_model == 'Positions' %}
<a href="/{{ start_model }}/{{action_models_s}}/{{ key }}/">
                                    {% elif action_model == 'Status' %}
<a href="/{{ start_model }}/{{action_models_s}}/{{ key }}/">
    {%else%}
                                <a href="/{{ action_model }}/{{ key }}/">
                                    {% endif %}
                                {{ value1 }}
                            </a></th>
                            {% endfor %}
                            {% endfor %}
                            {% endfor %}
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% endif %}
                <p class="paginator">

                    {{array_of_data|length}} {{ ru_name_all }}
                </p>
            </form>
        </div>
    </div>
    {% if action_model == 'Incidents'%}<a href="{% url 'Incidents_map'%}">Просмотреть все</a>{% endif %}
    {% if action_model == 'Subdivisions'%}<a href="{% url 'Subdivision_map'%}">Просмотреть все</a>{% endif %}
</div>
{% endblock %}