Graduation_Work_With_Django/Graduation_Work_With_Django/urls.py
from django.contrib import admin
from django.urls import path, include

handler403 = 'RRIT.views.handler403'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('RRIT.urls')),
    path('Incidents/', include('Incidents.urls')),
    path('users/', include('users.urls', namespace="users")),
    path('Subdivisions/', include('Subdivisions.urls')),
   # path("__debug__/", include("debug_toolbar.urls")),
]

Graduation_Work_With_Django/Incidents/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    # ------Incidents------
    path('', incidents_all, name='Incidents_all'),  # http://127.0.0.1:8000/Incidents - Incidents из мейн файла urls
    path('<int:IncidentId>/', incidents_id, name='Incidents_ID'),  # http://127.0.0.1:8000/Incidents/id/
    path('<int:IncidentId>/change/', incidents_change, name='Incidents_change'),  # http://127.0.0.1:8000/Incidents/id/change
    path('<int:IncidentId>/delete/', incidents_delete, name='Incidents_delete'),    # http://127.0.0.1:8000/Incidents/id/delete
    path('?', incidents_search, name='Incidents_search'),
    path('add/', incidents_add, name='Incidents_add'),
    path('map/', incidents_map, name='Incidents_map'),
    # -----Status------
    path('Status/', incidents_status, name='Incidents_status'),
    path('Status/?', incidents_status_search, name='Status_search'),
    path('Status/add/', incidents_status_add, name='Status_add'),
    path('Status/<int:StatusID>/', incidents_status_id, name='StatusID'),
    path('Status/<int:StatusID>/change/', incidents_status_change, name='Status_change'),
    path('Status/<int:StatusID>/delete/', incidents_status_delete, name='Status_delete'),
    # -----Specification------
    path('Specification/', incidents_specification, name='Incidents_specification'),
    path('Specification/?', incidents_specification_search, name='Specification_search'),
    path('Specification/add/', incidents_specification_add, name='Incidents_specification_add'),
    path('Specification/<int:SpecificationsId>/', incidents_specification_id, name='Specification_ID'),
    path('Specification/<int:SpecificationsId>/change/', incidents_specification_change, name='Specification_change'),
    path('Specification/<int:SpecificationsId>/delete/', incidents_specification_delete, name='Specification_delete'),
]
handler404 = 'Incidents.views.pageNotFound'

Graduation_Work_With_Django/RRIT/urls.py
from django.urls import path

from users.views import login_user
from .views import *

urlpatterns = [
    path('', index, name='home'),
]

Graduation_Work_With_Django/Incidents/models.py
from django.db import models
import datetime

from users.models import User


# Create your models here.

class Specifications(models.Model):
    pattern = models.CharField(max_length=100, verbose_name='Характеристика происшествия')
    color = models.CharField(max_length=20, verbose_name='Цвет происшествия')

    list_display = ('pattern', 'color')
    search_fields = ['pattern', 'color']

    class Meta:
        verbose_name = "Спецификацию происшествия"
        verbose_name_plural = "Спецификации происшествий"

        permissions = [
            ("Incidents.specification_add", "Добавление спецификации происшествия"),
            ("Incidents.specification_change", "Изменение спецификации происшествия"),
            ("Incidents.specification_delete", "Удаление спецификации происшествия"),
            ("Incidents.specification_id", "Просмотр спецификации происшествия"),

            ("Incidents.specification_all", "Просмотр всех спецификаций в таблице"),
        ]

    def __str__(self):
        return self.pattern

class Status(models.Model):
    status = models.CharField(max_length=100, verbose_name='Статус происшествия')
    description = models.CharField(max_length=100, verbose_name='Описание статуса происшествия')

    list_display = ('status', 'description')
    search_fields = ['status', 'description']

    class Meta:
        verbose_name = "Статус происшествия"
        verbose_name_plural = "Статусы происшествий"
        permissions = [
            ("Incidents.status_add", "Добавление статуса происшествия"),
            ("Incidents.status_change", "Изменение статуса происшествия"),
            ("Incidents.status_delete", "Удаление статуса происшествия"),
            ("Incidents.status_id", "Просмотр статуса происшествия"),

            ("Incidents.status_all", "Просмотр всех статусов в таблице"),
        ]

    def __str__(self):
        return self.status

class Incidents(models.Model):
    address = models.CharField(max_length=255, verbose_name='Адрес')
    description = models.CharField(max_length=255, verbose_name='Описание',)
    latitude = models.FloatField(verbose_name='Широта')
    longitude = models.FloatField(verbose_name='Долгота')
    specification = models.ForeignKey(Specifications, on_delete = models.SET_DEFAULT, default=1, verbose_name='Спецификация происшествия')
    complete = models.BooleanField(default=False, null=True, blank=True)



    time_create = models.DateTimeField(verbose_name='Дата и время обнаружения происшествия', default=datetime.datetime.now(), blank=True)
    time_start = models.DateTimeField(verbose_name='Дата и время принятия решения',null=True, blank=True)
    time_end = models.DateTimeField(verbose_name='Дата и время ликвидирования происшествия',null=True, blank=True)


    status = models.ForeignKey(Status, on_delete = models.SET_DEFAULT,  verbose_name='Статус происшествия',default=3, blank=True, )

    user_create = models.ForeignKey(User, on_delete = models.SET_DEFAULT, default=1, verbose_name='Обнаружитель происшествия', blank=True, related_name='user_create')
    user_responsible = models.ForeignKey(User, on_delete = models.SET_DEFAULT, default=1, verbose_name='Ответственный за происшествие', blank=False, related_name='user_responsible')

    taken_measures = models.CharField(max_length=255, verbose_name='Принятые меры по ликвидации', null=True, blank=True)



    #электрики сообщат о происшествии диспетчеру, диспетчер - создание заявки о происшествии

    list_display = ('address','description', 'specification', 'user_create', 'status')
    search_fields = ['address', 'description','user_create']
    class Meta:
        verbose_name = "Происшествие"
        verbose_name_plural = "Происшествия"
        permissions = [
            ("Incidents.incidents_add", "Добавление происшествий"),
            ("Incidents.incidents_change", "Изменение происшествий"),
            ("Incidents.incidents_delete", "Удаление происшествий"),
            ("Incidents.incidents_id", "Просмотр происшествия"),
            ("Incidents.incidents_map", "Просмотр всех происшествий на карте"),

            ("Incidents.incidents_all", "Просмотр всех происшествий в таблице"),
        ]

    def __str__(self):
        return self.address

Graduation_Work_With_Django/Incidents/views.py
import json
import locale

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseNotFound, Http404
from django.shortcuts import render, redirect

from Graduation_Work_With_Django import settings
from .forms import AddIncidentsForm, AddSpecificationsForm, StatusForm
from .models import *
from RRIT.views import get_settings, get_search, permission_edit_required

@login_required
@permission_edit_required('Incidents.Incidents.incidents_all')
def incidents_all(request):
    if not request.user.is_authenticated:
        return redirect(settings.LOGIN_URL)
    if request.GET.get('search'):
        return incidents_search(request)
    else:
        data = get_settings(request, Incidents, 1)
        return render(request, 'RRIT/view_all.html',context=data)

@login_required
@permission_edit_required('Incidents.Incidents.incidents_id')
def incidents_id(request, IncidentId):
    data = get_settings(request,Incidents)
    try:
        incident_breadcrumb = Incidents.objects.select_related().get(pk = IncidentId)
    except Incidents.DoesNotExist:
        raise Http404("No MyModel matches the given query.")
    incidents = Incidents.objects.filter(pk=IncidentId).select_related().values('description', 'latitude', 'longitude', 'address', 'specification__pattern', 'specification__color', 'time_create', 'user_create__surname', 'user_create__name','user_create__lastname')
    data['breadcrumb_ru'] += " › " + incident_breadcrumb.description
    key1 = list(incidents)
    for res in key1:
        res['time_create'] = res['time_create'].strftime('%d %b. %Y  %H:%M')
    list_data_json = json.dumps(key1)
    if not incident_breadcrumb.taken_measures:
        incident_breadcrumb.taken_measures = 'Еще нет решения'
    data1 = {
        'incident':incident_breadcrumb,
        'data': list_data_json,
    }
    data = data | data1
    return render(request, 'Incidents/index.html', context=data)

@login_required
@permission_edit_required('Incidents.Incidents.incidents_all')
def incidents_search(request):
    arg = request.GET.get('search')
    data = get_search(request, Incidents, arg, 1)
    return render(request, 'RRIT/view_all.html', context=data)


@login_required
@permission_edit_required('Incidents.Incidents.incidents_map')
def incidents_map(request):
    if not request.user.is_authenticated:
        return redirect(settings.LOGIN_URL)
    data = get_settings(request,Incidents)
    incidents = Incidents.objects.select_related().values('description', 'latitude', 'longitude','address', 'specification__pattern', 'specification__color', 'time_create', 'user_create__surname', 'user_create__name','user_create__lastname')
    key1 = list(incidents)
    for res in key1:
        res['time_create'] = res['time_create'].strftime('%d %b. %Y  %H:%M')
    list_data_json = json.dumps(key1)
    data1 = {
        'data': list_data_json,
    }
    data = data | data1
    return render(request, 'Incidents/map.html', context=data)


@login_required
@permission_edit_required('Incidents.Incidents.incidents_add')
def incidents_add(request):
    if not request.user.is_authenticated:
        return redirect(settings.LOGIN_URL)
    if request.method == 'POST':
        form = AddIncidentsForm(request.POST)
        form.instance.user_create = request.user
        if form.is_valid():
            obj = form.save()
            obj.time_create = datetime.datetime.now()
            obj.save()
            return redirect('Incidents_ID', obj.pk)
    else:

        form = AddIncidentsForm()
    data = get_settings(request,Incidents)
    data1 = {
        'form': form,
    }
    data = data | data1
    return render(request, 'Incidents/add.html',  context=data)
@login_required
@permission_edit_required('Incidents.Incidents.incidents_change')
def incidents_change(request, IncidentId):
    if not request.user.is_authenticated:
        return redirect(settings.LOGIN_URL)
    incident_breadcrumb = Incidents.objects.select_related().get(pk=IncidentId)
    time_start = incident_breadcrumb.time_start
    status = incident_breadcrumb.status
    taken_measures = incident_breadcrumb.taken_measures
    event_check = incident_breadcrumb.status.status
    if request.method == 'POST':
        form = AddIncidentsForm(request.POST, instance=incident_breadcrumb)
        if form.is_valid():
            obj = form.save()
            if request.POST.get('taken_measures', '') != '' and event_check == 'Обнаружено':
                obj.time_start = datetime.datetime.now()
                obj.status = Status.objects.select_related().get(status='В работе')
                obj.save()
            else:
                obj.time_start = time_start
                obj.status = status
                obj.taken_measures = taken_measures
            if request.POST.get('complete', '') != '':
                obj.time_end = datetime.datetime.now()
                obj.status = Status.objects.select_related().get(status='Ликвидировано')
                obj.save()

            obj.save()
            return redirect('Incidents_ID', obj.pk)
    else:
        form = AddIncidentsForm()
        form.fields['address'].widget.attrs['value'] = incident_breadcrumb.address
        form.fields['latitude'].widget.attrs['value'] = incident_breadcrumb.latitude
        form.fields['longitude'].widget.attrs['value'] = incident_breadcrumb.longitude
        form.fields['specification'].initial = incident_breadcrumb.specification.pk
    incident = Incidents.objects.select_related().filter(pk=IncidentId).values('address', 'description', 'latitude', 'longitude',
                                                              'specification__pattern', 'specification__color',
                                                              'time_create', 'user_create__surname', 'user_create__name',
                                                              'user_create__lastname')
    key1 = list(incident)
    key1[0]['time_create'] = key1[0]['time_create'].strftime('%d %b. %Y  %H:%M')
    list_data_json = json.dumps(key1)
    status_help = status.status
    data = get_settings(request,Incidents)
    data['breadcrumb_ru'] += " › " + incident_breadcrumb.description
    data1 = {
        'data': list_data_json,
        'form': form,
        'incident': incident_breadcrumb,
        'status_help':status_help,
    }
    data = data | data1
    return render(request, 'Incidents/change.html', context=data)
@login_required
@permission_edit_required('Incidents.Incidents.incidents_delete')
def incidents_delete(request, IncidentId):
    if not request.user.is_authenticated:
        return redirect(settings.LOGIN_URL)
    incident_breadcrumb = Incidents.objects.select_related().get(pk=IncidentId)
    incident_breadcrumb.delete()
    return redirect('Incidents_all')

def pageNotFound(request, exception):
    return HttpResponseNotFound('Страница инцидентов не найдена')
@login_required
@permission_edit_required('Incidents.Incidents.specification_all')
def incidents_specification(request):
    if not request.user.is_authenticated:
        return redirect(settings.LOGIN_URL)
    data = get_settings(request,Specifications, 1)
    data['action_models_s'] = 'Specification'
    data['action_model'] = 'Specifications'
    data1 = {
        'start_model': 'Incidents',
        'add': 'add/'
    }
    data = data | data1
    return render(request, 'RRIT/view_all.html',context=data)
@login_required
@permission_edit_required('Incidents.Incidents.specification_add')
def incidents_specification_add(request):
    if not request.user.is_authenticated:
        return redirect(settings.LOGIN_URL)
    if request.method == 'POST':
        form = AddSpecificationsForm(request.POST)
        if form.is_valid():
            obj = form.save()
            return redirect('Specification_ID', obj.pk)
    else:
        data = get_settings(request,Specifications)
        form = AddSpecificationsForm()
    data['action_model'] = 'Specifications'
    data1 = {
            'form': form,
        }
    data = data | data1

    return render(request, 'Specifications/add_specification.html', context=data )
@login_required
@permission_edit_required('Incidents.Incidents.specification_id')
def incidents_specification_id(request, SpecificationsId):
    if not request.user.is_authenticated:
        return redirect(settings.LOGIN_URL)
    specification = Specifications.objects.select_related().get(pk=SpecificationsId)

    data = get_settings(request,Specifications)
    data['action_model'] = 'Specifications'
    data1 = {
        'specification':specification,
    }
    data = data | data1

    return render(request, 'Specifications/id_specification.html', context=data)
@login_required
@permission_edit_required('Incidents.Incidents.specification_change')
def incidents_specification_change(request, SpecificationsId):
    if not request.user.is_authenticated:
        return redirect(settings.LOGIN_URL)
    specification = Specifications.objects.select_related().get(pk=SpecificationsId)
    if request.method == 'POST':
        form = AddSpecificationsForm(request.POST, instance=specification)
        if form.is_valid():
            obj = form.save()
            return redirect('Specification_ID', obj.pk)
    else:

        form = AddSpecificationsForm()
        form.fields['pattern'].widget.attrs['value'] = specification.pattern
        form.fields['color'].widget.attrs['value'] = specification.color

    data = get_settings(request,Specifications)
    data['action_model'] = 'Specifications'
    data1 = {
        'form': form,
        'specification': specification,
    }
    data = data | data1
    return render(request, 'Specifications/change_specification.html', context=data)
@login_required
@permission_edit_required('Incidents.Incidents.specification_delete')
def incidents_specification_delete(request, SpecificationsId):
    if not request.user.is_authenticated:
        return redirect(settings.LOGIN_URL)

Graduation_Work_With_Django/Incidents/templates/Status/add_status.html
{% extends "RRIT/index.html" %}
{% load i18n admin_urls static admin_list %}

{% block extrastyle %}
{{ block.super }}

<script src="{% url 'admin:jsi18n' %}"></script>

{% endblock %}

{% block extrahead %}
{{ block.super }}
{{ media.js }}
<link rel="stylesheet" href="{% static "admin/css/forms.css" %}">
<script src="{% static "bootstrap/js/bootstrap.bundle.min.js" %}"></script>

<link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.css" %} " />
{% endblock %}

{% block bodyclass %} app-{{ action_model }} model-{{ action_models_s }} change-list{% endblock %}
{% block sidebar %}
{% endblock %}
{% block nav-breadcrumbs %}
{% include "RRIT/navigation.html" %}

{% endblock %}


{% block nav-sidebar %}
{% include "RRIT/nav_sidebar.html" %}
{% endblock %}
{% block content %}
<div class="container1">
    <div class="row1">
        <div class="col-sm">
            <div style="text-align: center; font-size: 1rem; font-weight: 400; line-height: 1.5;">Добавить новый статус происшествий</div></div>
    </div>
    </div>


<fieldset class="module aligned ">
    <form action="" method="post">
                {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
        <div class="form-row field-">
                <div>
                        <div class="flex-container">
                                <label class="required" for="id_pattern">{{ f.label }}</label>
                                {{ f }}
                        </div>
                </div>
        </div>
        {% endfor %}
        <div class="submit-row">
                <button type="submit" class="btn btn-primary w-50" style="align:center;  margin-left: auto; margin-right: auto;">Добавить спецификацию</button>
        </div>
        </form>
</fieldset>
{% endblock %}

Graduation_Work_With_Django/Incidents/templates/Status/change_status.html
{% extends "RRIT/index.html" %}
{% load i18n admin_urls static admin_list %}

{% block extrastyle %}
{{ block.super }}

<script src="{% url 'admin:jsi18n' %}"></script>

{% endblock %}

{% block extrahead %}
{{ block.super }}
{{ media.js }}
<link rel="stylesheet" href="{% static "admin/css/forms.css" %}">
<script src="{% static "bootstrap/js/bootstrap.bundle.min.js" %}"></script>

<link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.css" %} " />
{% endblock %}

{% block bodyclass %} app-{{ action_model }} model-{{ action_models_s }} change-list{% endblock %}
{% block sidebar %}
{% endblock %}
{% block nav-breadcrumbs %}
{% include "RRIT/navigation.html" %}

{% endblock %}


{% block nav-sidebar %}
{% include "RRIT/nav_sidebar.html" %}
{% endblock %}
{% block content %}
<div class="container1">
    <div class="row1">
        <div class="col-sm">
            <div style="text-align: center; font-size: 1rem; font-weight: 400; line-height: 1.5;">Изменить статус происшествий</div></div>
    </div>
    </div>
<fieldset class="module aligned ">
    <form action="" method="post">
                {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
        <div class="form-row field-">
                <div>
                        <div class="flex-container">
                                <label class="required" for="id_pattern">{{ f.label }}</label>
                                {{ f }}
                        </div>
                </div>
        </div>
        {% endfor %}
        <div class="submit-row">
                <button type="submit" class="btn btn-primary w-50" style="align:center;  margin-left: auto; margin-right: auto;">Сохранить изменения спецификации</button>
        </div>
        </form>
</fieldset>
{% endblock %}

Graduation_Work_With_Django/Incidents/templates/Status/id_status.html
{% extends "RRIT/index.html" %}
{% load i18n admin_urls static admin_list %}

{% block extrastyle %}
{{ block.super }}

<script src="{% url 'admin:jsi18n' %}"></script>

{% endblock %}

{% block extrahead %}
{{ block.super }}
{{ media.js }}
<link rel="stylesheet" href="{% static "admin/css/forms.css" %}">
<script src="{% static "bootstrap/js/bootstrap.bundle.min.js" %}"></script>

<link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.css" %} " />
{% endblock %}

{% block bodyclass %} app-{{ action_model }} model-{{ action_models_s }} change-list{% endblock %}
{% block sidebar %}
{% endblock %}
{% block nav-breadcrumbs %}
{% include "RRIT/navigation.html" %}

{% endblock %}


{% block nav-sidebar %}
{% include "RRIT/nav_sidebar.html" %}
{% endblock %}
{% block content %}
<div class="container1">
    <div class="row1">
        <div class="col-sm">
            <div style="text-align: left; font-size: 1rem; font-weight: 400; line-height: 1.5;">Информация об статусе происшествий '{{ status.status}}'</div></div>
    </div>
    </div>

<fieldset class="module aligned ">
<div class="form-row field-">
                <div>
                        <div class="flex-container">
                                <label class="required" for="id_status">Статус происшествия</label>
                                <input type="text" name="pattern" value="{{status.status}}" required="" id="id_status" readonly class="vTextField">
                        </div>
                </div>
        </div>
    <div class="form-row field-">
                <div>
                        <div class="flex-container">
                                <label class="required" for="id_description">Описание статуса происшествия</label>
                                <input type="text" name="pattern" value="{{status.description}}" required="" id="id_description" readonly class="vTextField">
                        </div>
                </div>
        </div>
</fieldset>
                <div class="submit-row">
                    <a type="submit" class="btn btn-primary" href="change/" style="color: white;">Изменить</a>
                    <a type="submit" class="btn btn-danger" href="delete/" style="color: white; margin-left: auto;">Удалить</a>
                </div>


{% endblock %}