Graduation_Work_With_Django/Graduation_Work_With_Django/urls.py
from django.contrib import admin
from django.urls import path, include

handler403 = 'RRIT.views.handler403'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('RRIT.urls')),
    path('Incidents/', include('Incidents.urls')),
    path('users/', include('users.urls', namespace="users")),
    path('Subdivisions/', include('Subdivisions.urls')),
   # path("__debug__/", include("debug_toolbar.urls")),
]

Graduation_Work_With_Django/RRIT/urls.py
from django.urls import path

from users.views import login_user
from .views import *

urlpatterns = [
    path('', index, name='home'),
]

Graduation_Work_With_Django/users/urls.py
from django.urls import path

from .views import *

app_name = "users"

urlpatterns = [
    path('login/', login_user, name='login'),  # http://127.0.0.1:8000/Incidents/id/
    path('logout/', logout_user, name='logout'),  # http://127.0.0.1:8000/Incidents/id/
    path('', users_all, name='Users_all'),  # http://127.0.0.1:8000/Incidents - Users из мейн файла urls

    path('Position/', users_positions, name='users_positions'),  # http://127.0.0.1:8000/Incidents - Users из мейн файла urls
    path('Position/?', users_positions_search, name='Positions_search'),
    path('Position/<int:PositionID>/', users_positions_id, name='Positions_id'),
    path('Position/add/', users_positions_add, name='Positions_add'),
    path('Position/<int:PositionID>/change/', users_positions_change, name='Positions_change'),
    path('Position/<int:PositionID>/delete/', users_positions_delete, name='Positions_delete'),

    path('<int:UsersID>/', user_id, name='User_ID'),  # http://127.0.0.1:8000/Incidents/id/
    path('<int:UsersID>/delete/', user_delete, name='user_delete'),  # http://127.0.0.1:8000/Incidents/id/
    path('?', users_search, name='Users_search'),
]

Graduation_Work_With_Django/users/models.py
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.db import models
from django.utils import timezone

from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, Group, Permission

from Subdivisions.models import Subdivisions



class Positions(models.Model):
    positions = models.CharField(max_length=255, verbose_name="Наименование должности")

    list_display = ('positions', )
    search_fields = ['positions', ]

    class Meta:
        verbose_name = "Должность"
        verbose_name_plural = "Должности"

        permissions = [
            ("users.position_add", "Добавление должностей"),
            ("users.position_change", "Изменение должностей"),
            ("users.position_delete", "Удаление должностей"),
            ("users.position_id", "Просмотр должности"),

            ("users.position_all", "Просмотр всех должностей в таблице"),
        ]

    def __str__(self):
        return self.positions


class UserManager(BaseUserManager):
    def create_user(self, email, name, surname, lastname, password=None):
        if not email:
            raise ValueError("User must have an email")
        if not password:
            raise ValueError("User must have a password")
        if not name:
            raise ValueError("User must have a name")
        if not surname:
            raise ValueError("User must have a surname")
        if not lastname:
            raise ValueError("User must have a lastname")
        user = self.model(
            email=self.normalize_email(email)
        )
        user.name = name
        user.surname = surname
        user.lastname = lastname
        user.fullname = surname + ' ' + name + ' ' + lastname
        user.set_password(password)  # change password to hash

        user.is_staff = True
        user.is_active = True
        user.is_superuser = True

        user.save(using=self._db)
        return user

    #def create_staffuser(self, email,  name, surname, lastname, password=None):
        #user = self.create_user(
            #email,
           # name,
            #surname,
            #lastname,
            #password=password,
            #is_staff=True,
        #)
        #return user

    def create_superuser(self, email, name, surname, lastname, password=None):
        user = self.create_user(
            email,
            name,
            surname,
            lastname,
            password=password,
        )
        return user

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length=255, unique=True, verbose_name="e-mail")
    name = models.CharField(max_length=50, verbose_name="Имя")
    surname = models.CharField(max_length=50, verbose_name="Фамилия")
    lastname = models.CharField(max_length=50, verbose_name="Отчество")
    subdivision = models.ForeignKey(Subdivisions, on_delete = models.SET_DEFAULT, default=1, verbose_name='Подразделение', blank=True)
    fullname = models.CharField(max_length=255, verbose_name="Полное имя", default='Нет полного имени')

    position = models.ForeignKey(Positions, on_delete = models.SET_DEFAULT, verbose_name='Должность', blank=True, default=10)
    # default - должность с наименованием "нет должности"

    is_staff = models.BooleanField(u'staff status', default=False,
                                   help_text=u'Designates whether the user can log into this admin '
                                             'site.')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name', 'surname', 'lastname']  # Email & Password are required by default.
    list_display = ('id', 'email', 'name', 'surname', 'lastname','position', 'subdivision')
    search_fields = ['email', 'name', 'surname', 'lastname', 'subdivision' ]
    objects = UserManager()

    def get_full_name(self):
        # The user is identified by their email address
        return self.email
    def get_full(self):
        return self.name + ' ' + self.surname
    def get_short_name(self):
         # The user is identified by their email address
         return self.email


    def __str__(self):              # __unicode__ on Python 2
         return self.surname +' ' + self.name  +' ' + self.lastname + ' Подразделение: ' + self.subdivision.abbreviation

    class Meta:
        verbose_name = "Пользователя"
        verbose_name_plural = "Пользователи"

        permissions = [
            ("users.user_id", "Просмотр пользователей"),
            ("users.user_delete", "Удаление пользователей"),
            ("users.user_all", "Просмотр всех пользователей в таблице"),
        ]

Graduation_Work_With_Django/users/forms.py
from django import forms

from users.models import Positions
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from users.models import User
from django.contrib import admin
from django.utils.translation import gettext_lazy as _
class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = '__all__'

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField(
        label=_("Password"),
        help_text=_(
            '<a href="{}">Изменить пароль</a>'
        ),
    )
    class Meta:
        model = User
        fields = '__all__'
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        password = self.fields.get("password")
        if password:
            password.help_text = password.help_text.format(
                f"../../{self.instance.pk}/password/"
            )



class LoginUserForm(forms.Form):
    email = forms.CharField(label="Email", widget=forms.TextInput(attrs={
    'autocapitalize':'none',
    'autofocus':'autofocus',
    'maxlength':'10',
    'required': 'required',
    'id':'id_username',
    'maxlength':'255',
    }))

    password = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={
    'id':"id_password",
        'autocomplete':"current-password",
    }))


class PositionForm(forms.ModelForm):
    class Meta:
        model = Positions
        fields = '__all__'
        widgets = {
            'positions': forms.TextInput(attrs={
                                              'placeholder': 'введите наименование должности',
                                              'maxlength': '255',
                                                'class': 'vTextField',
                                              }
                                       ),
        }
        labels = {
        }
        error_messages = {
            'positions': {
                'max_length': "Максимальное количество символов - 255.",
                'required': "Обязательное поле - Должность."
            },
        }

Graduation_Work_With_Django/users/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseNotFound, HttpResponseRedirect

from Graduation_Work_With_Django import settings
from .forms import LoginUserForm, PositionForm
from .models import *
from RRIT.views import get_settings, get_search, permission_edit_required


def login_user(request):
    if request.method == 'POST':
        form=LoginUserForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, email=cd['email'],
                                password=cd['password'])
            if user:
                login(request, user)
                return HttpResponseRedirect(reverse('home'))
    else:
        form= LoginUserForm()
    return render(request, 'users/login.html', {'form':form})

@login_required
def logout_user(request):
    logout(request)
    return redirect('users:login')
@login_required
@permission_edit_required('users.users.user_all')
def users_all(request):
    if not request.user.is_authenticated:
        return redirect(settings.LOGIN_URL)
    data = get_settings(request, User,1)
    data1 = {
        'add': 'add/',
    }

    data = data | data1
    return render(request, 'RRIT/view_all.html',context=data)
@login_required
@permission_edit_required('users.users.user_id')
def user_id(request, UsersID):
    user = User.objects.get(pk=UsersID)
    password_hash = user.password.split('$')
    solt = password_hash[2][0:6]
    hash = password_hash[3][0:6]

    data = get_settings(request, User)
    data['breadcrumb_ru'] += " › " + user.surname + " " + user.name + ' ' + user.lastname + " " + user.email
    data1 = {
        'solt': solt,
        'hash': hash,
        'user': user,
    }
    data = data | data1
    return render(request, 'users/user.html',context=data)
@login_required
@permission_edit_required('users.users.user_delete')
def user_delete(request, UsersID):
    if not request.user.is_authenticated:
        return redirect(settings.LOGIN_URL)
    user = User.objects.select_related().get(pk=UsersID)
    user.delete()
    return redirect('users:Users_all')
@login_required
@permission_edit_required('users.users.user_all')
def users_search(request):
    if not request.user.is_authenticated:
        return redirect(settings.LOGIN_URL)
    arg = request.GET.get('search')
    data = get_search(request,User,arg)
    return render(request, 'RRIT/view_all.html',context=data)

@login_required
@permission_edit_required('users.users.position_add')
def users_positions_add(request):
    if not request.user.is_authenticated:
        return redirect(settings.LOGIN_URL)
    if request.method == 'POST':
        form = PositionForm(request.POST)
        if form.is_valid():
            obj = form.save()
            return redirect('users:Positions_id', obj.pk)
    else:
        data = get_settings(request, Positions)
        form = PositionForm()
    data['action_model'] = 'Positions'
    data1 = {
            'form': form,
        }
    data = data | data1

    return render(request, 'Position/add_position.html', context=data )
@login_required
@permission_edit_required('users.users.position_all')
def users_positions_search(request):
    if not request.user.is_authenticated:
        return redirect(settings.LOGIN_URL)
    arg = request.GET.get('search')
    data = get_search(request,Positions, arg, 1)
    data['action_model'] = 'Positions'
    return render(request, 'RRIT/view_all.html',context=data)
@login_required
@permission_edit_required('users.users.position_all')
def users_positions(request):
    if not request.user.is_authenticated:
        return redirect(settings.LOGIN_URL)
    data = get_settings(request, Positions,1)
    data['action_models_s'] = 'Position'
    data['action_model'] = 'Positions'
    data1 = {
        'start_model': 'users',
        'add': 'add/'
    }
    data = data | data1
    return render(request, 'RRIT/view_all.html',context=data)


@login_required
@permission_edit_required('users.users.position_id')
def users_positions_id(request, PositionID):
    if not request.user.is_authenticated:
        return redirect(settings.LOGIN_URL)
    position = Positions.objects.select_related().get(pk=PositionID)

    data = get_settings(request, Positions)
    data['action_model'] = 'Positions'
    data1 = {
        'position':position,
    }
    data = data | data1
    return render(request, 'Position/id_position.html',context=data)
@login_required
@permission_edit_required('users.users.position_change')
def users_positions_change(request, PositionID):
    if not request.user.is_authenticated:
        return redirect(settings.LOGIN_URL)
    position = Positions.objects.select_related().get(pk=PositionID)
    if request.method == 'POST':
        form = PositionForm(request.POST, instance=position)
        if form.is_valid():
            obj = form.save()
            return redirect('users:Positions_id', obj.pk)
    else:
        form = PositionForm()
        form.fields['positions'].widget.attrs['value'] = position.positions

    data = get_settings(request, Positions)
    data['action_model'] = 'Positions'
    data1 = {
        'form': form,
        'position': position,
    }
    data = data | data1
    return render(request, 'Position/change_position.html', context=data)
@login_required
@permission_edit_required('users.users.position_delete')
def users_positions_delete(request, PositionID):
    if not request.user.is_authenticated:
        return redirect(settings.LOGIN_URL)
    position = Positions.objects.get(pk=PositionID)
    position.delete()
    return redirect('users:users_positions')
def pageNotFound(request, exception):
    return HttpResponseNotFound('Страница users не найдена')

Graduation_Work_With_Django/users/templates/users/login.html
{% extends "RRIT/index.html" %}
{% load i18n admin_urls static %}

{% block extrastyle %}
{{ block.super }}

{{ form.media }}

{% endblock %}
{% block extrahead %}<link rel="stylesheet" href="{% static "admin/css/login.css" %}">{% endblock %}
{% block bodyclass %}login{% endblock %}





{% block content %}
{% block usertools %}
{% endblock %}
<div id="content-main">


<form action="" method="post" id="">
  {% csrf_token %}
  <div class="form-row">
    <label for="id_username" class="required">Логин:</label>
    {{form.email}}
  </div>
  <div class="form-row">
    <label for="id_password" class="required">Пароль:</label>
     {{ form.password }}
    <input type="hidden" name="next" value="{{ next }}">
  </div>
  <div class="submit-row">
    <input type="submit" value="{% translate 'Log in' %}">
  </div>
</form>

</div>
{% block sidebar %}{% endblock %}
{% endblock %}

Graduation_Work_With_Django/users/templates/users/user.html
{% extends "RRIT/index.html" %}
{% load i18n admin_urls static admin_list %}

{% block extrastyle %}
<link rel="stylesheet" href="/static/admin/css/forms.css">
<link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.css" %} " />
{{ block.super }}

{% endblock %}

{% block extrahead %}

{{ block.super }}

{{ media.js }}
{% endblock %}

{% block bodyclass %} app-{{ action_model }} model-{{ action_models_s }} change-list{% endblock %}

{% block sidebar %}
{% endblock %}

{% block nav-breadcrumbs %}

{% include "RRIT/navigation.html" %}

{% endblock %}


{% block nav-sidebar %}
{% include "RRIT/nav_sidebar.html" %}
{% endblock %}
{% block content %}
<div id="content" class="colM">
    <h1>Изменить пользователя</h1>
    <h2>{{ user.surname }} {{ user.name }} {{ user.lastname }} {{ user.email }}</h2>
    <div id="content-main">
        <ul class="object-tools">
            <li>
                <a href="/admin/users/user/1/history/" class="historylink">История</a>
            </li>
        </ul>
       <form method="post" id="user_form" novalidate><input type="hidden" name="csrfmiddlewaretoken"
                                                             value="G3XKQFKx6t054ehhKR34o9lvNCfWz2cJWnIHzkqE1RSTzyMPCTxnqhDxcA5cZlt0">
            <div>
                <fieldset class="module aligned ">
                    <div class="form-row field-email">
                        <div>
                            <div class="flex-container">
                                <label class="required" for="id_email">E-mail:</label>
                                <input type="email" name="email" value="{{ user.email }}" class="vTextField"
                                       maxlength="255" required id="id_email" readonly>
                            </div>
                        </div>
                    </div>
                    <div class="form-row field-password">
                        <div>
                            <div class="flex-container">
                                <label>Password:</label>
                                <div disabled id="id_password">
                                    <strong>алгоритм</strong>:
                                    <bdi>pbkdf2_sha256</bdi>
                                    <strong>итерации</strong>:
                                    <bdi>600000</bdi>
                                    <strong>соль</strong>:
                                    <bdi>{{solt}}****************</bdi>
                                    <strong>хэш</strong>:
                                    <bdi>{{hash}}**************************************</bdi>
                                </div>
                            </div>
                        </div>
                    </div>
                </fieldset>
                <fieldset class="module aligned ">
                    <h2>Личные данные</h2>
                    <div class="form-row field-name">
                        <div>
                            <div class="flex-container">
                                <label class="required" for="id_name">Имя:</label>
                                <input type="text" name="name" value="{{ user.name }}" class="vTextField" maxlength="255"
                                       required id="id_name" readonly>
                            </div>
                        </div>
                    </div>
                    <div class="form-row field-surname">
                        <div>
                            <div class="flex-container">
                                <label class="required" for="id_surname">Фамилия:</label>
                                <input type="text" name="surname" value="{{ user.surname }}" class="vTextField" maxlength="255"
                                       required id="id_surname" readonly>
                            </div>
                        </div>
                    </div>
                    <div class="form-row field-lastname">
                        <div>
                            <div class="flex-container">
                                <label class="required" for="id_lastname">Отчество:</label>
                                <input type="text" name="lastname" value="{{ user.lastname }}" class="vTextField" maxlength="255"
                                       required id="id_lastname" readonly>

                            </div>
                        </div>
                    </div>
                </fieldset>
                <div class="submit-row">
                    <a type="submit" class="btn btn-primary" href="change/" style="color: white;">Изменить</a>
                    <a type="submit" class="btn btn-danger" href="delete/" style="color: white; margin-left: auto;">Удалить</a>
                </div>
            </div>
        </form>
    </div>
    <br class="clear">
</div>
{% endblock %}